import 'package:addisecom/models/supplier_model.dart';

var suppliers = [
  new Supplier(
    id: 1,
    code: "567890789009",
    fname: "Sup 1",
    lname: "Lname",
    email: "Email",
    url: "imageurl",
    country: "Ethiopia",
    city: "Addis Ababa",
    logo: "imageurl",
    address1: "add",
    address2: "add2",
    phonenum: "phone num",
  ),
  new Supplier(
    id: 2,
    code: "567890789009",
    fname: "H&M",
    lname: "Lname",
    email: "Email",
    url: "imageurl",
    country: "Ethiopia",
    city: "Addis Ababa",
    logo: "imageurl",
    address1: "add",
    address2: "add2",
    phonenum: "phone num",
  ),
  new Supplier(
    id: 3,
    code: "567890789009",
    fname: "Nike",
    lname: "Lname",
    email: "Email",
    url: "imageurl",
    country: "Ethiopia",
    city: "Addis Ababa",
    logo: "imageurl",
    address1: "add",
    address2: "add2",
    phonenum: "phone num",
  ),
  new Supplier(
    id: 4,
    code: "567890789009",
    fname: "Sup 4",
    lname: "Lname",
    email: "Email",
    url: "imageurl",
    country: "Ethiopia",
    city: "Addis Ababa",
    logo: "imageurl",
    address1: "add",
    address2: "add2",
    phonenum: "phone num",
  ),
  new Supplier(
    id: 5,
    code: "567890789009",
    fname: "FirstName",
    lname: "Lname",
    email: "Email",
    url: "imageurl",
    country: "Ethiopia",
    city: "Addis Ababa",
    logo: "imageurl",
    address1: "add",
    address2: "add2",
    phonenum: "phone num",
  ),
  new Supplier(
    id: 6,
    code: "567890789009",
    fname: "FirstName",
    lname: "Lname",
    email: "Email",
    url: "imageurl",
    country: "Ethiopia",
    city: "Addis Ababa",
    logo: "imageurl",
    address1: "add",
    address2: "add2",
    phonenum: "phone num",
  ),
];
